on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: avibregistry.azurecr.io
        username: ${{ secrets.acr_avibregistry_username }}
        password: ${{ secrets.acr_avibregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "Dockerfile" -t avibregistry.azurecr.io/avibclusterc055:${{ github.sha }}
        docker push avibregistry.azurecr.io/avibclusterc055:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_avibcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep avibclusterc055 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace avibclusterc055`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: avibclusterc055
        container-registry-url: avibregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_avibregistry_username }}
        container-registry-password: ${{ secrets.acr_avibregistry_password }}
        secret-name: avibclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: avibclusterc055
        manifests: |
          ./manifests/deployment-c055.yml
          ./manifests/service-c055.yml
          ./manifests/ingress-c055.yml
        images: |
          avibregistry.azurecr.io/avibclusterc055:${{ github.sha }}
        imagepullsecrets: |
          avibclusterdockerauth